language: generic
os:
  - linux
  - osx

cache:
  directories:
    - texlive

before_install:
  # TeX Live
  - |
    case $TRAVIS_OS_NAME in
      linux)
        arch=x86_64-linux
        ;;
      osx)
        arch=x86_64-darwin
        ;;
    esac
  - |
    if [ ! -e ./texlive/bin/$arch/tlmgr ]; then
      wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz -O - | tar -x --gzip
      echo "
      selected_scheme scheme-minimal
      TEXDIR ./texlive
      TEXMFCONFIG ~/.texlive/texmf-config
      TEXMFHOME ~/texmf
      TEXMFLOCAL ./texlive/texmf-local
      TEXMFSYSCONFIG ./texlive/texmf-config
      TEXMFSYSVAR ./texlive/texmf-var
      TEXMFVAR ~/.texlive/texmf-var
      collection-fontsrecommended 1
      collection-latex 1
      option_doc 0
      option_src 0
      " | sed -e 's/^ *//' >texlive.profile
      ./install-tl-20*/install-tl --profile texlive.profile
    fi
  - export PATH=$(pwd)/texlive/bin/$arch:$PATH
  - tlmgr update --self

script:
  MAKE_COLORS=always make check
